dist: trusty
sudo: false

language: node_js
node_js: "6.8"

before_install:
  - git clone https://github.com/dapphub/dapp; cd dapp; make link prefix=/tmp/dep/; cd ..
  - wget https://github.com/rainbreak/solidity-static/releases/download/v0.4.8/solc
  - install solc /tmp/dep/bin/
  - wget https://github.com/dapphub/ethrun/releases/download/v0.0.0/ethrun-v0.0.0-linux
  - install ethrun-v0.0.0-linux /tmp/dep/bin/ethrun
  - export PATH=$PATH:/tmp/dep/bin/

install:
  - echo "no install"

script:
  - dapp test
